apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sock-shop-cert
  namespace: istio-system
spec:
  commonName: "sock-shop.bet777.win"
  dnsNames:
  - "sock-shop.bet777.win"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: sock-shop-cert
