---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: sock-shop
  labels:
    name: orders
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: orders
