apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-hello-world
  namespace: istio-system
spec:
  commonName: "hello-world.bet777.win"
  dnsNames:
  - "hello-world.bet777.win"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: cert-hello-world
