apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-guestbook
  namespace: istio-system
spec:
  commonName: "guestbook.bet777.win"
  dnsNames:
  - "guestbook.bet777.win"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: cert-guestbook
