resources:
- slots777-namespace.yaml
- cert-de-slots777.yaml
- gw-de-slots777.yaml
- vs-webclient-slots777.yaml
- webclient-svc-slots777.yaml
- webclient-deployment-slots777.yaml
patches:
- path: webclient-lifecycle-patch.json
  target:
    group: apps
    kind: Deployment
    name: de-webclient-slots777
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization