namePrefix: dev-
nameSuffix: "-001"

resources:
- slots777-namespace.yaml
- cert-de-slots777.yaml
- gw-de-slots777.yaml
- vs-webclient-slots777.yaml
- webclient-svc-slots777.yaml
- webclient-deployment-slots777.yaml

vars:
- name: MY_SERVICE_NAME
  objref:
    kind: Service
    name: de-webclient-slots777
    apiVersion: v1