apiVersion: v1
kind: Service
metadata:
  name: de-webclient-slots777
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http-webclient
  selector:
    app: de-webclient-slots777
