apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-webclient-slots777
  namespace: slots777win
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: de-webclient-slots777
  template:
    metadata:
      labels:
        app: de-webclient-slots777
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        lifecycle:
          postStart:
            exec:
              command:
                ['/bin/sh', '-c', 'echo Hello shell demo > /usr/share/nginx/html/index.html']
        ports:
        - containerPort: 80